# smtp.host=smtp.office365.com
# smtp.port=587
# smtp.username=hoevelaken.duurzaam@outlook.com
# smtp.password=X5m7r8KB1pTD2nJiqqKw
# smtp.ssl=false
# smtp.tls=true

smtp.host=smtp-mail.outlook.com
smtp.port=587
smtp.username=hoevelaken.duurzaam@outlook.com
smtp.password=X5m7r8KB1pTD2nJiqqKw
smtp.ssl=false
smtp.tls=true

# Beveiligingsinstellingen
# smtp.ssl=false
# smtp.tls=true

# Timeout instellingen (in milliseconden)
smtp.connectiontimeout=5000
smtp.timeout=5000
smtp.writetimeout=5000

# Debug modus
smtp.debug=false

# Afzender informatie
mail.from.name=Hoevelaken Duurzaam Buurkracht
mail.from.email=hoevelaken.duurzaam@outlook.com

# Batch instellingen
batch.delay=1000  # Wacht 1 seconde tussen e-mails
batch.max.retries=3
